# 42. CD-OPE-S Pretrained 학습실험

A2-A5를 seed 반복으로 학습합니다. 기본값은 안전하게 `RUN_TRAIN=False`입니다.
실제 실행 시 `RUN_TRAIN=True`, `TRAIN_SEEDS=[0,1,2]`, `EPOCHS=30`으로 둡니다.

비교군:

- A2: `g_cd`
- A3: `gl_cd`
- A4: `gl_cd_consistency`
- A5: `gl_cd_consistency_style`

In [1]:
from pathlib import Path
import sys
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

NOTEBOOK_DIR = Path.cwd()
if not (NOTEBOOK_DIR / "ch4_utils.py").exists():
    matches = list(Path.cwd().glob("Deeplearning/*/4장/ch4_utils.py")) + list(Path.cwd().glob("**/ch4_utils.py"))
    if matches:
        NOTEBOOK_DIR = matches[0].parent
    else:
        NOTEBOOK_DIR = Path("Deeplearning") / "Vision 응용" / "4장"
sys.path.insert(0, str(NOTEBOOK_DIR))

from ch4_utils import *

paths = find_ch4_paths()
set_korean_font()
set_seed(41)
paths

Chapter4Paths(chapter4_dir=WindowsPath('C:/Users/준승/Desktop/2026-1/Study/Deeplearning/Vision 응용/4장'), chapter3_dir=WindowsPath('C:/Users/준승/Desktop/2026-1/Study/Deeplearning/Vision 응용/3장'), runs_root=WindowsPath('C:/Users/준승/Desktop/2026-1/Study/Deeplearning/Vision 응용/4장/runs'), manifest_root=WindowsPath('C:/Users/준승/Desktop/2026-1/Study/Deeplearning/Vision 응용/4장/runs/manifests'), design_path=WindowsPath('C:/Users/준승/Desktop/2026-1/Study/Deeplearning/Vision 응용/4장/chapter4_cd_ope_s_architecture_design.md'), validity_path=WindowsPath('C:/Users/준승/Desktop/2026-1/Study/Deeplearning/Vision 응용/4장/runs/chapter4_cd_ope_s_design_validity_review.md'))

## 42-1. manifest와 실험 계획

In [2]:
manifests = create_ch4_manifests(max_per_cell=None, seed=41)
run_root = paths.runs_root / "cd_ope_s" / "runs"

variants = [
    {
        "variant": "g_cd",
        "use_global": True,
        "use_local": False,
        "consistency": False,
        "style_suppression": False,
    },
    {
        "variant": "gl_cd",
        "use_global": True,
        "use_local": True,
        "consistency": False,
        "style_suppression": False,
    },
    {
        "variant": "gl_cd_consistency",
        "use_global": True,
        "use_local": True,
        "consistency": True,
        "style_suppression": False,
    },
    {
        "variant": "gl_cd_consistency_style",
        "use_global": True,
        "use_local": True,
        "consistency": True,
        "style_suppression": True,
    },
]
display(pd.DataFrame(variants))

,variant,use_global,use_local,consistency,style_suppression
0,g_cd,True,False,False,False
1,gl_cd,True,True,False,False
2,gl_cd_consistency,True,True,True,False
3,gl_cd_consistency_style,True,True,True,True

## 42-2. 학습 실행

In [3]:
RUN_TRAIN = True
TRAIN_SEEDS = [0, 1, 2]
EPOCHS = 30
BATCH_SIZE = 8
BASE_LR = 1e-4
BRANCH_LR_MULT = 3.0

if RUN_TRAIN:
    for variant in variants:
        for seed in TRAIN_SEEDS:
            run_dir = run_root / variant["variant"] / f"seed_{seed}"
            if (run_dir / "sample_metrics.csv").exists():
                print("skip existing:", run_dir)
                continue
            print("training:", variant["variant"], "seed", seed)
            train_cd_ope_s_experiment(
                manifests["train"],
                manifests["eval_matched"],
                run_dir,
                variant=variant["variant"],
                epochs=EPOCHS,
                batch_size=BATCH_SIZE,
                base_lr=BASE_LR,
                branch_lr_mult=BRANCH_LR_MULT,
                seed=seed,
                use_global=variant["use_global"],
                use_local=variant["use_local"],
                consistency=variant["consistency"],
                style_suppression=variant["style_suppression"],
                local_kernel_size=15,
                consistency_weight=0.25,
                consistency_ce_weight=0.5,
                style_weight=0.05,
                ramp_epochs=5,
            )
else:
    print("RUN_TRAIN=False: 설정을 확인했습니다. 실제 학습은 True로 바꾸고 실행하세요.")

training: g_cd seed 0

C:\Users\준승\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loading weights:   0%|          | 0/208 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 208/208 [00:00<00:00, 13703.22it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b0-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([6])
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 256, 1, 1]) vs model:torch.Size([6, 256, 1, 1])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

epoch 01 | loss=1.0528 | ce=1.0528 | cons=0.0000 | style=0.0000 | ag=0.0050 | al=0.0000

epoch 02 | loss=0.4927 | ce=0.4927 | cons=0.0000 | style=0.0000 | ag=0.0087 | al=0.0000

epoch 03 | loss=0.3293 | ce=0.3293 | cons=0.0000 | style=0.0000 | ag=0.0139 | al=0.0000

epoch 04 | loss=0.2495 | ce=0.2495 | cons=0.0000 | style=0.0000 | ag=0.0212 | al=0.0000

epoch 05 | loss=0.2067 | ce=0.2067 | cons=0.0000 | style=0.0000 | ag=0.0260 | al=0.0000

epoch 06 | loss=0.1786 | ce=0.1786 | cons=0.0000 | style=0.0000 | ag=0.0310 | al=0.0000

epoch 07 | loss=0.1537 | ce=0.1537 | cons=0.0000 | style=0.0000 | ag=0.0363 | al=0.0000

epoch 08 | loss=0.1326 | ce=0.1326 | cons=0.0000 | style=0.0000 | ag=0.0398 | al=0.0000

epoch 09 | loss=0.1164 | ce=0.1164 | cons=0.0000 | style=0.0000 | ag=0.0422 | al=0.0000

epoch 10 | loss=0.1026 | ce=0.1026 | cons=0.0000 | style=0.0000 | ag=0.0455 | al=0.0000

epoch 11 | loss=0.0915 | ce=0.0915 | cons=0.0000 | style=0.0000 | ag=0.0476 | al=0.0000

epoch 12 | loss=0.0822 | ce=0.0822 | cons=0.0000 | style=0.0000 | ag=0.0492 | al=0.0000

epoch 13 | loss=0.0733 | ce=0.0733 | cons=0.0000 | style=0.0000 | ag=0.0490 | al=0.0000

epoch 14 | loss=0.0661 | ce=0.0661 | cons=0.0000 | style=0.0000 | ag=0.0514 | al=0.0000

epoch 15 | loss=0.0600 | ce=0.0600 | cons=0.0000 | style=0.0000 | ag=0.0527 | al=0.0000

epoch 16 | loss=0.0561 | ce=0.0561 | cons=0.0000 | style=0.0000 | ag=0.0539 | al=0.0000

epoch 17 | loss=0.0509 | ce=0.0509 | cons=0.0000 | style=0.0000 | ag=0.0539 | al=0.0000

epoch 18 | loss=0.0482 | ce=0.0482 | cons=0.0000 | style=0.0000 | ag=0.0553 | al=0.0000

epoch 19 | loss=0.0449 | ce=0.0449 | cons=0.0000 | style=0.0000 | ag=0.0554 | al=0.0000

epoch 20 | loss=0.0418 | ce=0.0418 | cons=0.0000 | style=0.0000 | ag=0.0567 | al=0.0000

epoch 21 | loss=0.0401 | ce=0.0401 | cons=0.0000 | style=0.0000 | ag=0.0575 | al=0.0000

epoch 22 | loss=0.0382 | ce=0.0382 | cons=0.0000 | style=0.0000 | ag=0.0577 | al=0.0000

epoch 23 | loss=0.0369 | ce=0.0369 | cons=0.0000 | style=0.0000 | ag=0.0598 | al=0.0000

epoch 24 | loss=0.0345 | ce=0.0345 | cons=0.0000 | style=0.0000 | ag=0.0601 | al=0.0000

epoch 25 | loss=0.0327 | ce=0.0327 | cons=0.0000 | style=0.0000 | ag=0.0612 | al=0.0000

epoch 26 | loss=0.0306 | ce=0.0306 | cons=0.0000 | style=0.0000 | ag=0.0611 | al=0.0000

epoch 27 | loss=0.0307 | ce=0.0307 | cons=0.0000 | style=0.0000 | ag=0.0597 | al=0.0000

epoch 28 | loss=0.0299 | ce=0.0299 | cons=0.0000 | style=0.0000 | ag=0.0601 | al=0.0000

epoch 29 | loss=0.0280 | ce=0.0280 | cons=0.0000 | style=0.0000 | ag=0.0613 | al=0.0000

epoch 30 | loss=0.0281 | ce=0.0281 | cons=0.0000 | style=0.0000 | ag=0.0612 | al=0.0000

training: g_cd seed 1

Loading weights:   0%|          | 0/208 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 208/208 [00:00<00:00, 13652.82it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b0-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([6])
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 256, 1, 1]) vs model:torch.Size([6, 256, 1, 1])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

epoch 01 | loss=1.1250 | ce=1.1250 | cons=0.0000 | style=0.0000 | ag=0.0014 | al=0.0000

epoch 02 | loss=0.5356 | ce=0.5356 | cons=0.0000 | style=0.0000 | ag=0.0021 | al=0.0000

epoch 03 | loss=0.3640 | ce=0.3640 | cons=0.0000 | style=0.0000 | ag=0.0038 | al=0.0000

epoch 04 | loss=0.2756 | ce=0.2756 | cons=0.0000 | style=0.0000 | ag=0.0075 | al=0.0000

epoch 05 | loss=0.2230 | ce=0.2230 | cons=0.0000 | style=0.0000 | ag=0.0117 | al=0.0000

epoch 06 | loss=0.1906 | ce=0.1906 | cons=0.0000 | style=0.0000 | ag=0.0168 | al=0.0000

epoch 07 | loss=0.1649 | ce=0.1649 | cons=0.0000 | style=0.0000 | ag=0.0229 | al=0.0000

epoch 08 | loss=0.1422 | ce=0.1422 | cons=0.0000 | style=0.0000 | ag=0.0245 | al=0.0000

epoch 09 | loss=0.1246 | ce=0.1246 | cons=0.0000 | style=0.0000 | ag=0.0280 | al=0.0000

epoch 10 | loss=0.1107 | ce=0.1107 | cons=0.0000 | style=0.0000 | ag=0.0269 | al=0.0000

epoch 11 | loss=0.0988 | ce=0.0988 | cons=0.0000 | style=0.0000 | ag=0.0287 | al=0.0000

epoch 12 | loss=0.0889 | ce=0.0889 | cons=0.0000 | style=0.0000 | ag=0.0306 | al=0.0000

epoch 13 | loss=0.0790 | ce=0.0790 | cons=0.0000 | style=0.0000 | ag=0.0309 | al=0.0000

epoch 14 | loss=0.0722 | ce=0.0722 | cons=0.0000 | style=0.0000 | ag=0.0317 | al=0.0000

epoch 15 | loss=0.0655 | ce=0.0655 | cons=0.0000 | style=0.0000 | ag=0.0319 | al=0.0000

epoch 16 | loss=0.0604 | ce=0.0604 | cons=0.0000 | style=0.0000 | ag=0.0333 | al=0.0000

epoch 17 | loss=0.0553 | ce=0.0553 | cons=0.0000 | style=0.0000 | ag=0.0338 | al=0.0000

epoch 18 | loss=0.0506 | ce=0.0506 | cons=0.0000 | style=0.0000 | ag=0.0345 | al=0.0000

epoch 19 | loss=0.0477 | ce=0.0477 | cons=0.0000 | style=0.0000 | ag=0.0350 | al=0.0000

epoch 20 | loss=0.0450 | ce=0.0450 | cons=0.0000 | style=0.0000 | ag=0.0353 | al=0.0000

epoch 21 | loss=0.0423 | ce=0.0423 | cons=0.0000 | style=0.0000 | ag=0.0361 | al=0.0000

epoch 22 | loss=0.0400 | ce=0.0400 | cons=0.0000 | style=0.0000 | ag=0.0365 | al=0.0000

epoch 23 | loss=0.0390 | ce=0.0390 | cons=0.0000 | style=0.0000 | ag=0.0374 | al=0.0000

epoch 24 | loss=0.0363 | ce=0.0363 | cons=0.0000 | style=0.0000 | ag=0.0381 | al=0.0000

epoch 25 | loss=0.0335 | ce=0.0335 | cons=0.0000 | style=0.0000 | ag=0.0385 | al=0.0000

epoch 26 | loss=0.0325 | ce=0.0325 | cons=0.0000 | style=0.0000 | ag=0.0396 | al=0.0000

epoch 27 | loss=0.0316 | ce=0.0316 | cons=0.0000 | style=0.0000 | ag=0.0400 | al=0.0000

epoch 28 | loss=0.0300 | ce=0.0300 | cons=0.0000 | style=0.0000 | ag=0.0402 | al=0.0000

epoch 29 | loss=0.0285 | ce=0.0285 | cons=0.0000 | style=0.0000 | ag=0.0403 | al=0.0000

epoch 30 | loss=0.0281 | ce=0.0281 | cons=0.0000 | style=0.0000 | ag=0.0407 | al=0.0000

training: g_cd seed 2

Loading weights:   0%|          | 0/208 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 208/208 [00:00<00:00, 13710.97it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b0-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([6])
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 256, 1, 1]) vs model:torch.Size([6, 256, 1, 1])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

epoch 01 | loss=1.0677 | ce=1.0677 | cons=0.0000 | style=0.0000 | ag=0.0014 | al=0.0000

epoch 02 | loss=0.5152 | ce=0.5152 | cons=0.0000 | style=0.0000 | ag=0.0020 | al=0.0000

epoch 03 | loss=0.3470 | ce=0.3470 | cons=0.0000 | style=0.0000 | ag=0.0047 | al=0.0000

epoch 04 | loss=0.2626 | ce=0.2626 | cons=0.0000 | style=0.0000 | ag=0.0085 | al=0.0000

epoch 05 | loss=0.2160 | ce=0.2160 | cons=0.0000 | style=0.0000 | ag=0.0163 | al=0.0000

epoch 06 | loss=0.1827 | ce=0.1827 | cons=0.0000 | style=0.0000 | ag=0.0253 | al=0.0000

epoch 07 | loss=0.1558 | ce=0.1558 | cons=0.0000 | style=0.0000 | ag=0.0301 | al=0.0000

epoch 08 | loss=0.1347 | ce=0.1347 | cons=0.0000 | style=0.0000 | ag=0.0338 | al=0.0000

epoch 09 | loss=0.1200 | ce=0.1200 | cons=0.0000 | style=0.0000 | ag=0.0363 | al=0.0000

epoch 10 | loss=0.1073 | ce=0.1073 | cons=0.0000 | style=0.0000 | ag=0.0388 | al=0.0000

epoch 11 | loss=0.0976 | ce=0.0976 | cons=0.0000 | style=0.0000 | ag=0.0401 | al=0.0000

epoch 12 | loss=0.0877 | ce=0.0877 | cons=0.0000 | style=0.0000 | ag=0.0412 | al=0.0000

epoch 13 | loss=0.0786 | ce=0.0786 | cons=0.0000 | style=0.0000 | ag=0.0438 | al=0.0000

epoch 14 | loss=0.0729 | ce=0.0729 | cons=0.0000 | style=0.0000 | ag=0.0448 | al=0.0000

epoch 15 | loss=0.0643 | ce=0.0643 | cons=0.0000 | style=0.0000 | ag=0.0455 | al=0.0000

epoch 16 | loss=0.0595 | ce=0.0595 | cons=0.0000 | style=0.0000 | ag=0.0461 | al=0.0000

epoch 17 | loss=0.0550 | ce=0.0550 | cons=0.0000 | style=0.0000 | ag=0.0471 | al=0.0000

epoch 18 | loss=0.0513 | ce=0.0513 | cons=0.0000 | style=0.0000 | ag=0.0487 | al=0.0000

epoch 19 | loss=0.0479 | ce=0.0479 | cons=0.0000 | style=0.0000 | ag=0.0508 | al=0.0000

epoch 20 | loss=0.0453 | ce=0.0453 | cons=0.0000 | style=0.0000 | ag=0.0504 | al=0.0000

epoch 21 | loss=0.0424 | ce=0.0424 | cons=0.0000 | style=0.0000 | ag=0.0514 | al=0.0000

epoch 22 | loss=0.0399 | ce=0.0399 | cons=0.0000 | style=0.0000 | ag=0.0510 | al=0.0000

epoch 23 | loss=0.0381 | ce=0.0381 | cons=0.0000 | style=0.0000 | ag=0.0524 | al=0.0000

epoch 24 | loss=0.0360 | ce=0.0360 | cons=0.0000 | style=0.0000 | ag=0.0529 | al=0.0000

epoch 25 | loss=0.0346 | ce=0.0346 | cons=0.0000 | style=0.0000 | ag=0.0542 | al=0.0000

epoch 26 | loss=0.0344 | ce=0.0344 | cons=0.0000 | style=0.0000 | ag=0.0535 | al=0.0000

epoch 27 | loss=0.0310 | ce=0.0310 | cons=0.0000 | style=0.0000 | ag=0.0544 | al=0.0000

epoch 28 | loss=0.0296 | ce=0.0296 | cons=0.0000 | style=0.0000 | ag=0.0552 | al=0.0000

epoch 29 | loss=0.0288 | ce=0.0288 | cons=0.0000 | style=0.0000 | ag=0.0562 | al=0.0000

epoch 30 | loss=0.0279 | ce=0.0279 | cons=0.0000 | style=0.0000 | ag=0.0562 | al=0.0000

training: gl_cd seed 0

Loading weights:   0%|          | 0/208 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 208/208 [00:00<00:00, 11990.31it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b0-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([6])
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 256, 1, 1]) vs model:torch.Size([6, 256, 1, 1])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

epoch 01 | loss=1.0393 | ce=1.0393 | cons=0.0000 | style=0.0000 | ag=0.0019 | al=0.0042

epoch 02 | loss=0.4768 | ce=0.4768 | cons=0.0000 | style=0.0000 | ag=0.0024 | al=0.0056

epoch 03 | loss=0.3243 | ce=0.3243 | cons=0.0000 | style=0.0000 | ag=0.0050 | al=0.0060

epoch 04 | loss=0.2471 | ce=0.2471 | cons=0.0000 | style=0.0000 | ag=0.0096 | al=0.0073

epoch 05 | loss=0.2057 | ce=0.2057 | cons=0.0000 | style=0.0000 | ag=0.0157 | al=0.0098

epoch 06 | loss=0.1749 | ce=0.1749 | cons=0.0000 | style=0.0000 | ag=0.0229 | al=0.0146

epoch 07 | loss=0.1491 | ce=0.1491 | cons=0.0000 | style=0.0000 | ag=0.0266 | al=0.0183

epoch 08 | loss=0.1301 | ce=0.1301 | cons=0.0000 | style=0.0000 | ag=0.0313 | al=0.0207

epoch 09 | loss=0.1140 | ce=0.1140 | cons=0.0000 | style=0.0000 | ag=0.0346 | al=0.0215

epoch 10 | loss=0.1014 | ce=0.1014 | cons=0.0000 | style=0.0000 | ag=0.0358 | al=0.0213

epoch 11 | loss=0.0897 | ce=0.0897 | cons=0.0000 | style=0.0000 | ag=0.0375 | al=0.0202

epoch 12 | loss=0.0807 | ce=0.0807 | cons=0.0000 | style=0.0000 | ag=0.0374 | al=0.0205

epoch 13 | loss=0.0726 | ce=0.0726 | cons=0.0000 | style=0.0000 | ag=0.0397 | al=0.0207

epoch 14 | loss=0.0648 | ce=0.0648 | cons=0.0000 | style=0.0000 | ag=0.0411 | al=0.0208

epoch 15 | loss=0.0604 | ce=0.0604 | cons=0.0000 | style=0.0000 | ag=0.0409 | al=0.0205

epoch 16 | loss=0.0561 | ce=0.0561 | cons=0.0000 | style=0.0000 | ag=0.0407 | al=0.0224

epoch 17 | loss=0.0510 | ce=0.0510 | cons=0.0000 | style=0.0000 | ag=0.0415 | al=0.0212

epoch 18 | loss=0.0480 | ce=0.0480 | cons=0.0000 | style=0.0000 | ag=0.0428 | al=0.0213

epoch 19 | loss=0.0451 | ce=0.0451 | cons=0.0000 | style=0.0000 | ag=0.0435 | al=0.0226

epoch 20 | loss=0.0420 | ce=0.0420 | cons=0.0000 | style=0.0000 | ag=0.0448 | al=0.0214

epoch 21 | loss=0.0395 | ce=0.0395 | cons=0.0000 | style=0.0000 | ag=0.0461 | al=0.0210

epoch 22 | loss=0.0374 | ce=0.0374 | cons=0.0000 | style=0.0000 | ag=0.0466 | al=0.0216

epoch 23 | loss=0.0362 | ce=0.0362 | cons=0.0000 | style=0.0000 | ag=0.0480 | al=0.0221

epoch 24 | loss=0.0353 | ce=0.0353 | cons=0.0000 | style=0.0000 | ag=0.0489 | al=0.0230

epoch 25 | loss=0.0340 | ce=0.0340 | cons=0.0000 | style=0.0000 | ag=0.0493 | al=0.0223

epoch 26 | loss=0.0313 | ce=0.0313 | cons=0.0000 | style=0.0000 | ag=0.0494 | al=0.0223

epoch 27 | loss=0.0301 | ce=0.0301 | cons=0.0000 | style=0.0000 | ag=0.0503 | al=0.0224

epoch 28 | loss=0.0292 | ce=0.0292 | cons=0.0000 | style=0.0000 | ag=0.0511 | al=0.0216

epoch 29 | loss=0.0275 | ce=0.0275 | cons=0.0000 | style=0.0000 | ag=0.0514 | al=0.0224

epoch 30 | loss=0.0262 | ce=0.0262 | cons=0.0000 | style=0.0000 | ag=0.0524 | al=0.0229

training: gl_cd seed 1

Loading weights:   0%|          | 0/208 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 208/208 [00:00<00:00, 11367.86it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b0-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([6])
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 256, 1, 1]) vs model:torch.Size([6, 256, 1, 1])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

epoch 01 | loss=1.1000 | ce=1.1000 | cons=0.0000 | style=0.0000 | ag=0.0046 | al=-0.0021

epoch 02 | loss=0.5303 | ce=0.5303 | cons=0.0000 | style=0.0000 | ag=0.0067 | al=-0.0020

epoch 03 | loss=0.3642 | ce=0.3642 | cons=0.0000 | style=0.0000 | ag=0.0106 | al=-0.0020

epoch 04 | loss=0.2755 | ce=0.2755 | cons=0.0000 | style=0.0000 | ag=0.0168 | al=-0.0026

epoch 05 | loss=0.2223 | ce=0.2223 | cons=0.0000 | style=0.0000 | ag=0.0207 | al=-0.0030

epoch 06 | loss=0.1896 | ce=0.1896 | cons=0.0000 | style=0.0000 | ag=0.0219 | al=-0.0033

epoch 07 | loss=0.1627 | ce=0.1627 | cons=0.0000 | style=0.0000 | ag=0.0253 | al=-0.0085

epoch 08 | loss=0.1399 | ce=0.1399 | cons=0.0000 | style=0.0000 | ag=0.0278 | al=-0.0155

epoch 09 | loss=0.1233 | ce=0.1233 | cons=0.0000 | style=0.0000 | ag=0.0309 | al=-0.0206

epoch 10 | loss=0.1096 | ce=0.1096 | cons=0.0000 | style=0.0000 | ag=0.0311 | al=-0.0252

epoch 11 | loss=0.0984 | ce=0.0984 | cons=0.0000 | style=0.0000 | ag=0.0337 | al=-0.0302

epoch 12 | loss=0.0881 | ce=0.0881 | cons=0.0000 | style=0.0000 | ag=0.0349 | al=-0.0345

epoch 13 | loss=0.0793 | ce=0.0793 | cons=0.0000 | style=0.0000 | ag=0.0353 | al=-0.0378

epoch 14 | loss=0.0717 | ce=0.0717 | cons=0.0000 | style=0.0000 | ag=0.0357 | al=-0.0406

epoch 15 | loss=0.0654 | ce=0.0654 | cons=0.0000 | style=0.0000 | ag=0.0363 | al=-0.0426

epoch 16 | loss=0.0606 | ce=0.0606 | cons=0.0000 | style=0.0000 | ag=0.0383 | al=-0.0464

epoch 17 | loss=0.0556 | ce=0.0556 | cons=0.0000 | style=0.0000 | ag=0.0393 | al=-0.0461

epoch 18 | loss=0.0505 | ce=0.0505 | cons=0.0000 | style=0.0000 | ag=0.0400 | al=-0.0477

epoch 19 | loss=0.0481 | ce=0.0481 | cons=0.0000 | style=0.0000 | ag=0.0401 | al=-0.0494

epoch 20 | loss=0.0455 | ce=0.0455 | cons=0.0000 | style=0.0000 | ag=0.0396 | al=-0.0515

epoch 21 | loss=0.0420 | ce=0.0420 | cons=0.0000 | style=0.0000 | ag=0.0405 | al=-0.0523

epoch 22 | loss=0.0399 | ce=0.0399 | cons=0.0000 | style=0.0000 | ag=0.0433 | al=-0.0538

epoch 23 | loss=0.0378 | ce=0.0378 | cons=0.0000 | style=0.0000 | ag=0.0425 | al=-0.0552

epoch 24 | loss=0.0358 | ce=0.0358 | cons=0.0000 | style=0.0000 | ag=0.0438 | al=-0.0557

epoch 25 | loss=0.0337 | ce=0.0337 | cons=0.0000 | style=0.0000 | ag=0.0437 | al=-0.0557

epoch 26 | loss=0.0326 | ce=0.0326 | cons=0.0000 | style=0.0000 | ag=0.0433 | al=-0.0572

epoch 27 | loss=0.0315 | ce=0.0315 | cons=0.0000 | style=0.0000 | ag=0.0437 | al=-0.0588

epoch 28 | loss=0.0297 | ce=0.0297 | cons=0.0000 | style=0.0000 | ag=0.0448 | al=-0.0588

epoch 29 | loss=0.0288 | ce=0.0288 | cons=0.0000 | style=0.0000 | ag=0.0445 | al=-0.0589

epoch 30 | loss=0.0271 | ce=0.0271 | cons=0.0000 | style=0.0000 | ag=0.0450 | al=-0.0600

training: gl_cd seed 2

Loading weights:   0%|          | 0/208 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 208/208 [00:00<00:00, 8535.68it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b0-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([6])
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 256, 1, 1]) vs model:torch.Size([6, 256, 1, 1])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

epoch 01 | loss=1.0760 | ce=1.0760 | cons=0.0000 | style=0.0000 | ag=0.0020 | al=0.0025

epoch 02 | loss=0.5115 | ce=0.5115 | cons=0.0000 | style=0.0000 | ag=0.0044 | al=0.0044

epoch 03 | loss=0.3463 | ce=0.3463 | cons=0.0000 | style=0.0000 | ag=0.0094 | al=0.0058

epoch 04 | loss=0.2649 | ce=0.2649 | cons=0.0000 | style=0.0000 | ag=0.0166 | al=0.0076

epoch 05 | loss=0.2193 | ce=0.2193 | cons=0.0000 | style=0.0000 | ag=0.0238 | al=0.0110

epoch 06 | loss=0.1885 | ce=0.1885 | cons=0.0000 | style=0.0000 | ag=0.0305 | al=0.0176

epoch 07 | loss=0.1624 | ce=0.1624 | cons=0.0000 | style=0.0000 | ag=0.0379 | al=0.0264

epoch 08 | loss=0.1394 | ce=0.1394 | cons=0.0000 | style=0.0000 | ag=0.0419 | al=0.0265

epoch 09 | loss=0.1232 | ce=0.1232 | cons=0.0000 | style=0.0000 | ag=0.0444 | al=0.0276

epoch 10 | loss=0.1104 | ce=0.1104 | cons=0.0000 | style=0.0000 | ag=0.0469 | al=0.0281

epoch 11 | loss=0.0998 | ce=0.0998 | cons=0.0000 | style=0.0000 | ag=0.0483 | al=0.0262

epoch 12 | loss=0.0890 | ce=0.0890 | cons=0.0000 | style=0.0000 | ag=0.0495 | al=0.0265

epoch 13 | loss=0.0800 | ce=0.0800 | cons=0.0000 | style=0.0000 | ag=0.0508 | al=0.0260

epoch 14 | loss=0.0743 | ce=0.0743 | cons=0.0000 | style=0.0000 | ag=0.0525 | al=0.0270

epoch 15 | loss=0.0663 | ce=0.0663 | cons=0.0000 | style=0.0000 | ag=0.0522 | al=0.0270

epoch 16 | loss=0.0596 | ce=0.0596 | cons=0.0000 | style=0.0000 | ag=0.0548 | al=0.0268

epoch 17 | loss=0.0546 | ce=0.0546 | cons=0.0000 | style=0.0000 | ag=0.0549 | al=0.0275

epoch 18 | loss=0.0511 | ce=0.0511 | cons=0.0000 | style=0.0000 | ag=0.0574 | al=0.0275

epoch 19 | loss=0.0471 | ce=0.0471 | cons=0.0000 | style=0.0000 | ag=0.0582 | al=0.0269

epoch 20 | loss=0.0449 | ce=0.0449 | cons=0.0000 | style=0.0000 | ag=0.0582 | al=0.0266

epoch 21 | loss=0.0435 | ce=0.0435 | cons=0.0000 | style=0.0000 | ag=0.0597 | al=0.0273

epoch 22 | loss=0.0408 | ce=0.0408 | cons=0.0000 | style=0.0000 | ag=0.0613 | al=0.0275

epoch 23 | loss=0.0386 | ce=0.0386 | cons=0.0000 | style=0.0000 | ag=0.0619 | al=0.0258

epoch 24 | loss=0.0361 | ce=0.0361 | cons=0.0000 | style=0.0000 | ag=0.0624 | al=0.0265

epoch 25 | loss=0.0346 | ce=0.0346 | cons=0.0000 | style=0.0000 | ag=0.0634 | al=0.0265

epoch 26 | loss=0.0334 | ce=0.0334 | cons=0.0000 | style=0.0000 | ag=0.0641 | al=0.0280

epoch 27 | loss=0.0312 | ce=0.0312 | cons=0.0000 | style=0.0000 | ag=0.0651 | al=0.0278

epoch 28 | loss=0.0296 | ce=0.0296 | cons=0.0000 | style=0.0000 | ag=0.0650 | al=0.0272

epoch 29 | loss=0.0293 | ce=0.0293 | cons=0.0000 | style=0.0000 | ag=0.0660 | al=0.0272

epoch 30 | loss=0.0282 | ce=0.0282 | cons=0.0000 | style=0.0000 | ag=0.0659 | al=0.0267

training: gl_cd_consistency seed 0

Loading weights:   0%|          | 0/208 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 208/208 [00:00<00:00, 10290.22it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b0-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([6])
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 256, 1, 1]) vs model:torch.Size([6, 256, 1, 1])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

epoch 01 | loss=1.1374 | ce=1.0345 | cons=0.0007 | style=0.0000 | ag=0.0027 | al=0.0035

epoch 02 | loss=0.5750 | ce=0.4790 | cons=0.0005 | style=0.0000 | ag=0.0050 | al=0.0048

epoch 03 | loss=0.4055 | ce=0.3117 | cons=0.0002 | style=0.0000 | ag=0.0097 | al=0.0053

epoch 04 | loss=0.3274 | ce=0.2339 | cons=0.0002 | style=0.0000 | ag=0.0181 | al=0.0066

epoch 05 | loss=0.2854 | ce=0.1902 | cons=0.0001 | style=0.0000 | ag=0.0256 | al=0.0102

epoch 06 | loss=0.2371 | ce=0.1576 | cons=0.0002 | style=0.0000 | ag=0.0311 | al=0.0164

epoch 07 | loss=0.1981 | ce=0.1323 | cons=0.0002 | style=0.0000 | ag=0.0328 | al=0.0199

epoch 08 | loss=0.1702 | ce=0.1133 | cons=0.0002 | style=0.0000 | ag=0.0359 | al=0.0223

epoch 09 | loss=0.1485 | ce=0.0983 | cons=0.0002 | style=0.0000 | ag=0.0373 | al=0.0220

epoch 10 | loss=0.1301 | ce=0.0865 | cons=0.0002 | style=0.0000 | ag=0.0378 | al=0.0205

epoch 11 | loss=0.1140 | ce=0.0755 | cons=0.0002 | style=0.0000 | ag=0.0396 | al=0.0207

epoch 12 | loss=0.1019 | ce=0.0676 | cons=0.0002 | style=0.0000 | ag=0.0400 | al=0.0219

epoch 13 | loss=0.0919 | ce=0.0607 | cons=0.0002 | style=0.0000 | ag=0.0406 | al=0.0206

epoch 14 | loss=0.0837 | ce=0.0557 | cons=0.0003 | style=0.0000 | ag=0.0416 | al=0.0219

epoch 15 | loss=0.0764 | ce=0.0506 | cons=0.0002 | style=0.0000 | ag=0.0426 | al=0.0220

epoch 16 | loss=0.0700 | ce=0.0463 | cons=0.0003 | style=0.0000 | ag=0.0429 | al=0.0218

epoch 17 | loss=0.0648 | ce=0.0434 | cons=0.0002 | style=0.0000 | ag=0.0436 | al=0.0220

epoch 18 | loss=0.0608 | ce=0.0405 | cons=0.0002 | style=0.0000 | ag=0.0441 | al=0.0227

epoch 19 | loss=0.0576 | ce=0.0383 | cons=0.0002 | style=0.0000 | ag=0.0444 | al=0.0232

epoch 20 | loss=0.0538 | ce=0.0358 | cons=0.0002 | style=0.0000 | ag=0.0455 | al=0.0235

epoch 21 | loss=0.0508 | ce=0.0333 | cons=0.0002 | style=0.0000 | ag=0.0466 | al=0.0230

epoch 22 | loss=0.0489 | ce=0.0325 | cons=0.0002 | style=0.0000 | ag=0.0473 | al=0.0227

epoch 23 | loss=0.0459 | ce=0.0304 | cons=0.0002 | style=0.0000 | ag=0.0470 | al=0.0228

epoch 24 | loss=0.0443 | ce=0.0293 | cons=0.0002 | style=0.0000 | ag=0.0481 | al=0.0236

epoch 25 | loss=0.0426 | ce=0.0283 | cons=0.0002 | style=0.0000 | ag=0.0486 | al=0.0237

epoch 26 | loss=0.0404 | ce=0.0268 | cons=0.0002 | style=0.0000 | ag=0.0490 | al=0.0242

epoch 27 | loss=0.0379 | ce=0.0248 | cons=0.0002 | style=0.0000 | ag=0.0495 | al=0.0249

epoch 28 | loss=0.0360 | ce=0.0236 | cons=0.0002 | style=0.0000 | ag=0.0495 | al=0.0256

epoch 29 | loss=0.0345 | ce=0.0229 | cons=0.0002 | style=0.0000 | ag=0.0503 | al=0.0253

epoch 30 | loss=0.0327 | ce=0.0216 | cons=0.0002 | style=0.0000 | ag=0.0511 | al=0.0252

training: gl_cd_consistency seed 1

Loading weights:   0%|          | 0/208 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 208/208 [00:00<00:00, 10506.60it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b0-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([6])
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 256, 1, 1]) vs model:torch.Size([6, 256, 1, 1])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

epoch 01 | loss=1.1997 | ce=1.0915 | cons=0.0008 | style=0.0000 | ag=0.0054 | al=-0.0016

epoch 02 | loss=0.6327 | ce=0.5275 | cons=0.0004 | style=0.0000 | ag=0.0083 | al=-0.0011

epoch 03 | loss=0.4549 | ce=0.3496 | cons=0.0003 | style=0.0000 | ag=0.0129 | al=-0.0007

epoch 04 | loss=0.3620 | ce=0.2591 | cons=0.0002 | style=0.0000 | ag=0.0190 | al=-0.0009

epoch 05 | loss=0.3100 | ce=0.2065 | cons=0.0002 | style=0.0000 | ag=0.0233 | al=-0.0005

epoch 06 | loss=0.2577 | ce=0.1714 | cons=0.0002 | style=0.0000 | ag=0.0241 | al=-0.0006

epoch 07 | loss=0.2143 | ce=0.1428 | cons=0.0002 | style=0.0000 | ag=0.0261 | al=-0.0047

epoch 08 | loss=0.1828 | ce=0.1215 | cons=0.0002 | style=0.0000 | ag=0.0287 | al=-0.0110

epoch 09 | loss=0.1612 | ce=0.1069 | cons=0.0002 | style=0.0000 | ag=0.0296 | al=-0.0171

epoch 10 | loss=0.1440 | ce=0.0958 | cons=0.0002 | style=0.0000 | ag=0.0294 | al=-0.0230

epoch 11 | loss=0.1258 | ce=0.0834 | cons=0.0002 | style=0.0000 | ag=0.0322 | al=-0.0290

epoch 12 | loss=0.1128 | ce=0.0746 | cons=0.0002 | style=0.0000 | ag=0.0328 | al=-0.0340

epoch 13 | loss=0.1014 | ce=0.0672 | cons=0.0002 | style=0.0000 | ag=0.0319 | al=-0.0391

epoch 14 | loss=0.0915 | ce=0.0607 | cons=0.0002 | style=0.0000 | ag=0.0332 | al=-0.0429

epoch 15 | loss=0.0833 | ce=0.0556 | cons=0.0002 | style=0.0000 | ag=0.0339 | al=-0.0457

epoch 16 | loss=0.0750 | ce=0.0497 | cons=0.0002 | style=0.0000 | ag=0.0341 | al=-0.0476

epoch 17 | loss=0.0707 | ce=0.0466 | cons=0.0002 | style=0.0000 | ag=0.0355 | al=-0.0492

epoch 18 | loss=0.0662 | ce=0.0439 | cons=0.0003 | style=0.0000 | ag=0.0369 | al=-0.0519

epoch 19 | loss=0.0602 | ce=0.0397 | cons=0.0002 | style=0.0000 | ag=0.0365 | al=-0.0539

epoch 20 | loss=0.0575 | ce=0.0384 | cons=0.0002 | style=0.0000 | ag=0.0366 | al=-0.0548

epoch 21 | loss=0.0540 | ce=0.0358 | cons=0.0002 | style=0.0000 | ag=0.0378 | al=-0.0557

epoch 22 | loss=0.0516 | ce=0.0340 | cons=0.0002 | style=0.0000 | ag=0.0379 | al=-0.0575

epoch 23 | loss=0.0483 | ce=0.0319 | cons=0.0002 | style=0.0000 | ag=0.0385 | al=-0.0579

epoch 24 | loss=0.0465 | ce=0.0305 | cons=0.0002 | style=0.0000 | ag=0.0378 | al=-0.0582

epoch 25 | loss=0.0437 | ce=0.0291 | cons=0.0002 | style=0.0000 | ag=0.0390 | al=-0.0596

epoch 26 | loss=0.0408 | ce=0.0272 | cons=0.0002 | style=0.0000 | ag=0.0395 | al=-0.0612

epoch 27 | loss=0.0393 | ce=0.0257 | cons=0.0002 | style=0.0000 | ag=0.0404 | al=-0.0624

epoch 28 | loss=0.0372 | ce=0.0244 | cons=0.0002 | style=0.0000 | ag=0.0408 | al=-0.0632

epoch 29 | loss=0.0358 | ce=0.0236 | cons=0.0002 | style=0.0000 | ag=0.0418 | al=-0.0644

epoch 30 | loss=0.0341 | ce=0.0224 | cons=0.0002 | style=0.0000 | ag=0.0417 | al=-0.0656

training: gl_cd_consistency seed 2

Loading weights:   0%|          | 0/208 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 208/208 [00:00<00:00, 13732.77it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b0-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([6])
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 256, 1, 1]) vs model:torch.Size([6, 256, 1, 1])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

epoch 01 | loss=1.1749 | ce=1.0681 | cons=0.0008 | style=0.0000 | ag=0.0030 | al=0.0012

epoch 02 | loss=0.6122 | ce=0.5101 | cons=0.0005 | style=0.0000 | ag=0.0051 | al=0.0026

epoch 03 | loss=0.4395 | ce=0.3380 | cons=0.0003 | style=0.0000 | ag=0.0092 | al=0.0042

epoch 04 | loss=0.3508 | ce=0.2506 | cons=0.0002 | style=0.0000 | ag=0.0176 | al=0.0076

epoch 05 | loss=0.3050 | ce=0.2035 | cons=0.0001 | style=0.0000 | ag=0.0270 | al=0.0147

epoch 06 | loss=0.2585 | ce=0.1725 | cons=0.0002 | style=0.0000 | ag=0.0319 | al=0.0268

epoch 07 | loss=0.2155 | ce=0.1434 | cons=0.0002 | style=0.0000 | ag=0.0383 | al=0.0265

epoch 08 | loss=0.1842 | ce=0.1226 | cons=0.0002 | style=0.0000 | ag=0.0419 | al=0.0261

epoch 09 | loss=0.1629 | ce=0.1083 | cons=0.0002 | style=0.0000 | ag=0.0437 | al=0.0258

epoch 10 | loss=0.1442 | ce=0.0959 | cons=0.0002 | style=0.0000 | ag=0.0461 | al=0.0240

epoch 11 | loss=0.1292 | ce=0.0862 | cons=0.0002 | style=0.0000 | ag=0.0489 | al=0.0228

epoch 12 | loss=0.1163 | ce=0.0773 | cons=0.0002 | style=0.0000 | ag=0.0511 | al=0.0236

epoch 13 | loss=0.1025 | ce=0.0681 | cons=0.0002 | style=0.0000 | ag=0.0518 | al=0.0202

epoch 14 | loss=0.0910 | ce=0.0603 | cons=0.0002 | style=0.0000 | ag=0.0543 | al=0.0209

epoch 15 | loss=0.0821 | ce=0.0542 | cons=0.0002 | style=0.0000 | ag=0.0563 | al=0.0230

epoch 16 | loss=0.0768 | ce=0.0510 | cons=0.0003 | style=0.0000 | ag=0.0569 | al=0.0215

epoch 17 | loss=0.0691 | ce=0.0458 | cons=0.0002 | style=0.0000 | ag=0.0583 | al=0.0215

epoch 18 | loss=0.0651 | ce=0.0431 | cons=0.0002 | style=0.0000 | ag=0.0594 | al=0.0210

epoch 19 | loss=0.0602 | ce=0.0398 | cons=0.0002 | style=0.0000 | ag=0.0611 | al=0.0195

epoch 20 | loss=0.0562 | ce=0.0373 | cons=0.0002 | style=0.0000 | ag=0.0608 | al=0.0216

epoch 21 | loss=0.0536 | ce=0.0354 | cons=0.0002 | style=0.0000 | ag=0.0632 | al=0.0216

epoch 22 | loss=0.0517 | ce=0.0342 | cons=0.0002 | style=0.0000 | ag=0.0635 | al=0.0201

epoch 23 | loss=0.0496 | ce=0.0326 | cons=0.0002 | style=0.0000 | ag=0.0645 | al=0.0209

epoch 24 | loss=0.0466 | ce=0.0308 | cons=0.0002 | style=0.0000 | ag=0.0651 | al=0.0214

epoch 25 | loss=0.0442 | ce=0.0290 | cons=0.0002 | style=0.0000 | ag=0.0655 | al=0.0207

epoch 26 | loss=0.0423 | ce=0.0280 | cons=0.0002 | style=0.0000 | ag=0.0667 | al=0.0203

epoch 27 | loss=0.0405 | ce=0.0268 | cons=0.0002 | style=0.0000 | ag=0.0677 | al=0.0210

epoch 28 | loss=0.0392 | ce=0.0257 | cons=0.0002 | style=0.0000 | ag=0.0682 | al=0.0203

epoch 29 | loss=0.0374 | ce=0.0249 | cons=0.0002 | style=0.0000 | ag=0.0692 | al=0.0215

epoch 30 | loss=0.0361 | ce=0.0240 | cons=0.0002 | style=0.0000 | ag=0.0692 | al=0.0215

training: gl_cd_consistency_style seed 0

Loading weights:   0%|          | 0/208 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 208/208 [00:00<00:00, 11688.78it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b0-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([6])
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 256, 1, 1]) vs model:torch.Size([6, 256, 1, 1])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

epoch 01 | loss=1.1703 | ce=1.0541 | cons=0.0007 | style=1.1408 | ag=0.0028 | al=0.0035

epoch 02 | loss=0.6180 | ce=0.4962 | cons=0.0005 | style=1.1273 | ag=0.0054 | al=0.0048

epoch 03 | loss=0.4546 | ce=0.3237 | cons=0.0002 | style=1.1222 | ag=0.0100 | al=0.0055

epoch 04 | loss=0.3837 | ce=0.2417 | cons=0.0002 | style=1.1322 | ag=0.0148 | al=0.0073

epoch 05 | loss=0.3501 | ce=0.1938 | cons=0.0001 | style=1.1874 | ag=0.0167 | al=0.0107

epoch 06 | loss=0.3101 | ce=0.1607 | cons=0.0002 | style=1.3868 | ag=0.0219 | al=0.0143

epoch 07 | loss=0.2898 | ce=0.1401 | cons=0.0003 | style=1.6510 | ag=0.0279 | al=0.0164

epoch 08 | loss=0.2616 | ce=0.1216 | cons=0.0003 | style=1.6314 | ag=0.0307 | al=0.0194

epoch 09 | loss=0.2314 | ce=0.1055 | cons=0.0002 | style=1.4579 | ag=0.0338 | al=0.0216

epoch 10 | loss=0.2065 | ce=0.0947 | cons=0.0003 | style=1.3086 | ag=0.0354 | al=0.0203

epoch 11 | loss=0.1855 | ce=0.0835 | cons=0.0002 | style=1.2128 | ag=0.0369 | al=0.0207

epoch 12 | loss=0.1700 | ce=0.0746 | cons=0.0002 | style=1.1547 | ag=0.0404 | al=0.0212

epoch 13 | loss=0.1549 | ce=0.0658 | cons=0.0003 | style=1.1217 | ag=0.0432 | al=0.0196

epoch 14 | loss=0.1447 | ce=0.0592 | cons=0.0003 | style=1.1120 | ag=0.0446 | al=0.0201

epoch 15 | loss=0.1364 | ce=0.0534 | cons=0.0003 | style=1.1062 | ag=0.0467 | al=0.0205

epoch 16 | loss=0.1295 | ce=0.0494 | cons=0.0003 | style=1.1027 | ag=0.0481 | al=0.0191

epoch 17 | loss=0.1245 | ce=0.0464 | cons=0.0002 | style=1.1016 | ag=0.0497 | al=0.0182

epoch 18 | loss=0.1201 | ce=0.0432 | cons=0.0003 | style=1.1012 | ag=0.0517 | al=0.0189

epoch 19 | loss=0.1154 | ce=0.0399 | cons=0.0002 | style=1.1027 | ag=0.0530 | al=0.0189

epoch 20 | loss=0.1119 | ce=0.0377 | cons=0.0002 | style=1.1047 | ag=0.0543 | al=0.0187

epoch 21 | loss=0.1082 | ce=0.0347 | cons=0.0002 | style=1.1053 | ag=0.0551 | al=0.0186

epoch 22 | loss=0.1064 | ce=0.0340 | cons=0.0003 | style=1.1038 | ag=0.0572 | al=0.0179

epoch 23 | loss=0.1036 | ce=0.0322 | cons=0.0002 | style=1.1033 | ag=0.0588 | al=0.0190

epoch 24 | loss=0.1011 | ce=0.0304 | cons=0.0002 | style=1.1013 | ag=0.0598 | al=0.0194

epoch 25 | loss=0.0990 | ce=0.0294 | cons=0.0002 | style=1.1011 | ag=0.0606 | al=0.0192

epoch 26 | loss=0.0964 | ce=0.0274 | cons=0.0002 | style=1.1010 | ag=0.0620 | al=0.0198

epoch 27 | loss=0.0947 | ce=0.0262 | cons=0.0003 | style=1.1014 | ag=0.0630 | al=0.0197

epoch 28 | loss=0.0924 | ce=0.0246 | cons=0.0002 | style=1.1012 | ag=0.0646 | al=0.0197

epoch 29 | loss=0.0909 | ce=0.0238 | cons=0.0002 | style=1.1013 | ag=0.0655 | al=0.0203

epoch 30 | loss=0.0896 | ce=0.0229 | cons=0.0002 | style=1.1016 | ag=0.0667 | al=0.0211

training: gl_cd_consistency_style seed 1

Loading weights:   0%|          | 0/208 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 208/208 [00:00<00:00, 13169.33it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b0-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([6])
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 256, 1, 1]) vs model:torch.Size([6, 256, 1, 1])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

epoch 01 | loss=1.2287 | ce=1.1077 | cons=0.0008 | style=1.0961 | ag=0.0018 | al=-0.0017

epoch 02 | loss=0.6643 | ce=0.5359 | cons=0.0005 | style=1.0840 | ag=0.0029 | al=-0.0015

epoch 03 | loss=0.4917 | ce=0.3529 | cons=0.0003 | style=1.0847 | ag=0.0054 | al=-0.0011

epoch 04 | loss=0.4096 | ce=0.2614 | cons=0.0002 | style=1.1059 | ag=0.0106 | al=-0.0022

epoch 05 | loss=0.3707 | ce=0.2083 | cons=0.0002 | style=1.1610 | ag=0.0145 | al=-0.0044

epoch 06 | loss=0.3300 | ce=0.1764 | cons=0.0002 | style=1.3055 | ag=0.0179 | al=-0.0088

epoch 07 | loss=0.3042 | ce=0.1518 | cons=0.0003 | style=1.5738 | ag=0.0190 | al=-0.0210

epoch 08 | loss=0.2924 | ce=0.1350 | cons=0.0004 | style=1.8620 | ag=0.0190 | al=-0.0320

epoch 09 | loss=0.2619 | ce=0.1184 | cons=0.0003 | style=1.6984 | ag=0.0187 | al=-0.0381

epoch 10 | loss=0.2348 | ce=0.1072 | cons=0.0003 | style=1.5056 | ag=0.0192 | al=-0.0421

epoch 11 | loss=0.2115 | ce=0.0948 | cons=0.0002 | style=1.3846 | ag=0.0205 | al=-0.0435

epoch 12 | loss=0.1948 | ce=0.0865 | cons=0.0003 | style=1.2923 | ag=0.0215 | al=-0.0465

epoch 13 | loss=0.1788 | ce=0.0788 | cons=0.0003 | style=1.2116 | ag=0.0220 | al=-0.0470

epoch 14 | loss=0.1669 | ce=0.0727 | cons=0.0003 | style=1.1580 | ag=0.0223 | al=-0.0486

epoch 15 | loss=0.1553 | ce=0.0656 | cons=0.0002 | style=1.1359 | ag=0.0230 | al=-0.0502

epoch 16 | loss=0.1447 | ce=0.0583 | cons=0.0003 | style=1.1349 | ag=0.0234 | al=-0.0512

epoch 17 | loss=0.1391 | ce=0.0544 | cons=0.0003 | style=1.1382 | ag=0.0241 | al=-0.0533

epoch 18 | loss=0.1324 | ce=0.0498 | cons=0.0003 | style=1.1413 | ag=0.0247 | al=-0.0539

epoch 19 | loss=0.1267 | ce=0.0462 | cons=0.0003 | style=1.1367 | ag=0.0252 | al=-0.0535

epoch 20 | loss=0.1229 | ce=0.0447 | cons=0.0003 | style=1.1243 | ag=0.0260 | al=-0.0550

epoch 21 | loss=0.1171 | ce=0.0408 | cons=0.0002 | style=1.1143 | ag=0.0261 | al=-0.0567

epoch 22 | loss=0.1136 | ce=0.0387 | cons=0.0003 | style=1.1076 | ag=0.0273 | al=-0.0567

epoch 23 | loss=0.1101 | ce=0.0363 | cons=0.0002 | style=1.1059 | ag=0.0281 | al=-0.0575

epoch 24 | loss=0.1072 | ce=0.0342 | cons=0.0002 | style=1.1051 | ag=0.0292 | al=-0.0579

epoch 25 | loss=0.1048 | ce=0.0330 | cons=0.0002 | style=1.1026 | ag=0.0303 | al=-0.0580

epoch 26 | loss=0.1015 | ce=0.0308 | cons=0.0002 | style=1.1043 | ag=0.0306 | al=-0.0588

epoch 27 | loss=0.0995 | ce=0.0292 | cons=0.0002 | style=1.1036 | ag=0.0315 | al=-0.0595

epoch 28 | loss=0.0971 | ce=0.0277 | cons=0.0002 | style=1.1039 | ag=0.0323 | al=-0.0586

epoch 29 | loss=0.0957 | ce=0.0266 | cons=0.0003 | style=1.1055 | ag=0.0332 | al=-0.0609

epoch 30 | loss=0.0935 | ce=0.0253 | cons=0.0002 | style=1.1042 | ag=0.0335 | al=-0.0610

training: gl_cd_consistency_style seed 2

Loading weights:   0%|          | 0/208 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 208/208 [00:00<00:00, 12609.71it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b0-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([6])
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 256, 1, 1]) vs model:torch.Size([6, 256, 1, 1])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

epoch 01 | loss=1.1644 | ce=1.0486 | cons=0.0007 | style=1.1186 | ag=0.0017 | al=0.0018

epoch 02 | loss=0.6253 | ce=0.5027 | cons=0.0004 | style=1.1073 | ag=0.0023 | al=0.0027

epoch 03 | loss=0.4657 | ce=0.3328 | cons=0.0003 | style=1.1026 | ag=0.0040 | al=0.0042

epoch 04 | loss=0.3909 | ce=0.2475 | cons=0.0002 | style=1.1129 | ag=0.0066 | al=0.0072

epoch 05 | loss=0.3601 | ce=0.2017 | cons=0.0002 | style=1.1601 | ag=0.0084 | al=0.0125

epoch 06 | loss=0.3254 | ce=0.1724 | cons=0.0002 | style=1.3415 | ag=0.0106 | al=0.0220

epoch 07 | loss=0.3191 | ce=0.1500 | cons=0.0003 | style=1.9434 | ag=0.0212 | al=0.0269

epoch 08 | loss=0.3038 | ce=0.1310 | cons=0.0003 | style=2.2081 | ag=0.0209 | al=0.0314

epoch 09 | loss=0.2733 | ce=0.1166 | cons=0.0003 | style=1.9850 | ag=0.0251 | al=0.0320

epoch 10 | loss=0.2473 | ce=0.1049 | cons=0.0003 | style=1.8298 | ag=0.0290 | al=0.0306

epoch 11 | loss=0.2247 | ce=0.0961 | cons=0.0003 | style=1.6408 | ag=0.0309 | al=0.0309

epoch 12 | loss=0.2022 | ce=0.0859 | cons=0.0003 | style=1.4575 | ag=0.0346 | al=0.0303

epoch 13 | loss=0.1817 | ce=0.0772 | cons=0.0003 | style=1.3155 | ag=0.0358 | al=0.0283

epoch 14 | loss=0.1655 | ce=0.0695 | cons=0.0003 | style=1.2220 | ag=0.0385 | al=0.0272

epoch 15 | loss=0.1528 | ce=0.0628 | cons=0.0002 | style=1.1556 | ag=0.0416 | al=0.0280

epoch 16 | loss=0.1432 | ce=0.0582 | cons=0.0003 | style=1.1197 | ag=0.0444 | al=0.0274

epoch 17 | loss=0.1353 | ce=0.0528 | cons=0.0003 | style=1.1091 | ag=0.0468 | al=0.0279

epoch 18 | loss=0.1289 | ce=0.0487 | cons=0.0003 | style=1.1071 | ag=0.0484 | al=0.0287

epoch 19 | loss=0.1232 | ce=0.0450 | cons=0.0003 | style=1.1087 | ag=0.0495 | al=0.0281

epoch 20 | loss=0.1176 | ce=0.0412 | cons=0.0002 | style=1.1088 | ag=0.0523 | al=0.0278

epoch 21 | loss=0.1153 | ce=0.0395 | cons=0.0003 | style=1.1084 | ag=0.0533 | al=0.0279

epoch 22 | loss=0.1122 | ce=0.0377 | cons=0.0003 | style=1.1057 | ag=0.0553 | al=0.0270

epoch 23 | loss=0.1084 | ce=0.0349 | cons=0.0003 | style=1.1056 | ag=0.0565 | al=0.0274

epoch 24 | loss=0.1070 | ce=0.0342 | cons=0.0003 | style=1.1062 | ag=0.0584 | al=0.0280

epoch 25 | loss=0.1032 | ce=0.0315 | cons=0.0002 | style=1.1044 | ag=0.0594 | al=0.0277

epoch 26 | loss=0.1016 | ce=0.0309 | cons=0.0003 | style=1.1030 | ag=0.0605 | al=0.0282

epoch 27 | loss=0.0999 | ce=0.0297 | cons=0.0003 | style=1.1019 | ag=0.0624 | al=0.0276

epoch 28 | loss=0.0979 | ce=0.0282 | cons=0.0002 | style=1.1011 | ag=0.0635 | al=0.0283

epoch 29 | loss=0.0955 | ce=0.0269 | cons=0.0002 | style=1.1022 | ag=0.0644 | al=0.0284

epoch 30 | loss=0.0939 | ce=0.0256 | cons=0.0002 | style=1.1017 | ag=0.0652 | al=0.0288

## 42-3. 결과 수집

In [4]:
seed_metrics = collect_ch4_cd_ope_metrics(run_root=run_root)
if seed_metrics.empty:
    print("아직 CD-OPE-S 학습 run이 없습니다.")
else:
    display(seed_metrics)
    display(pd.read_csv(paths.runs_root / "cd_ope_s" / "cd_ope_s_summary.csv"))

,variant,model_seed,run_dir,mean_dice,seen_color_dice,heldout_color_dice,red_dice,purple_dice,worst_combo_dice,target_fnr,alpha_global,alpha_local
0,g_cd,0,C:\Users\준승\Desktop\2026-1\Study\Deeplearning\...,0.555547,0.558469,0.551165,0.530599,0.571731,0.160530,0.488617,0.061157,0.000000
1,g_cd,1,C:\Users\준승\Desktop\2026-1\Study\Deeplearning\...,0.593736,0.621262,0.552447,0.495976,0.608918,0.205672,0.429164,0.040685,0.000000
2,g_cd,2,C:\Users\준승\Desktop\2026-1\Study\Deeplearning\...,0.511495,0.526553,0.488908,0.478978,0.498838,0.101797,0.540872,0.056230,0.000000
3,gl_cd,0,C:\Users\준승\Desktop\2026-1\Study\Deeplearning\...,0.525958,0.560491,0.474159,0.411909,0.536410,0.189626,0.529936,0.052356,0.022873
4,gl_cd,1,C:\Users\준승\Desktop\2026-1\Study\Deeplearning\...,0.485473,0.535433,0.410532,0.382798,0.438267,0.142344,0.562911,0.045000,-0.060026
5,gl_cd,2,C:\Users\준승\Desktop\2026-1\Study\Deeplearning\...,0.501366,0.514625,0.481477,0.488751,0.474204,0.143862,0.547570,0.065900,0.026714
6,gl_cd_consistency,0,C:\Users\준승\Desktop\2026-1\Study\Deeplearning\...,0.603256,0.626133,0.568940,0.503065,0.634816,0.240694,0.436429,0.051055,0.025223
7,gl_cd_consistency,1,C:\Users\준승\Desktop\2026-1\Study\Deeplearning\...,0.566173,0.595692,0.521896,0.486591,0.557201,0.181444,0.478784,0.041712,-0.065609
8,gl_cd_consistency,2,C:\Users\준승\Desktop\2026-1\Study\Deeplearning\...,0.608428,0.619006,0.592562,0.581388,0.603735,0.232915,0.417324,0.069178,0.021453
9,gl_cd_consistency_style,0,C:\Users\준승\Desktop\2026-1\Study\Deeplearning\...,0.557728,0.578172,0.527062,0.481942,0.572182,0.164774,0.498809,0.066665,0.021097
10,gl_cd_consistency_style,1,C:\Users\준승\Desktop\2026-1\Study\Deeplearning\...,0.605464,0.621924,0.580775,0.531285,0.630264,0.226124,0.440375,0.033504,-0.061037
11,gl_cd_consistency_style,2,C:\Users\준승\Desktop\2026-1\Study\Deeplearning\...,0.534167,0.557178,0.499651,0.495517,0.503786,0.107830,0.516055,0.065198,0.028801

,variant,mean_dice_mean,mean_dice_std,mean_dice_count,seen_color_dice_mean,seen_color_dice_std,seen_color_dice_count,heldout_color_dice_mean,heldout_color_dice_std,heldout_color_dice_count,red_dice_mean,red_dice_std,red_dice_count,worst_combo_dice_mean,worst_combo_dice_std,worst_combo_dice_count,target_fnr_mean,target_fnr_std,target_fnr_count
0,g_cd,0.553593,0.041156,3,0.568761,0.048186,3,0.530840,0.036320,3,0.501851,0.026307,3,0.156000,0.052085,3,0.486218,0.055893,3
1,gl_cd,0.504266,0.020398,3,0.536850,0.022966,3,0.455390,0.039020,3,0.427819,0.054739,3,0.158611,0.026871,3,0.546806,0.016501,3
2,gl_cd_consistency,0.592619,0.023048,3,0.613610,0.015922,3,0.561133,0.035974,3,0.523682,0.050650,3,0.218351,0.032198,3,0.444179,0.031454,3
3,gl_cd_consistency_style,0.565786,0.036325,3,0.585758,0.033033,3,0.535829,0.041266,3,0.502915,0.025490,3,0.166242,0.059161,3,0.485080,0.039664,3